[package]
name = "physics-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
sprs = "0.11.0"
vek = { version = "0.10.0", default-features = false, features = ["libm"] }
